# Site settings
title: Blog de tecnologia da Dito
email: plataforma@dito.com.br
description: > # this means to ignore newlines until "baseurl:"
  Um lugar para a equipe FERA que faz a Dito funcionar falar sobre boas
  práticas, melhorias de código, refatoração, TDD, design patterns e mais, com
  foco em Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tecnologia.dito.com.br" # the base hostname & protocol for your site
twitter_username: ditointernet
github_username:  ditointernet

# Build settings
markdown: kramdown

# Custom configuration
timezone: America/Sao_Paulo
permalink: /posts/:title/
